<a href="https://colab.research.google.com/github/NRJaggers/Applied-Stochastic-Processes/blob/main/PracticeProblems/CTMC_Stationary_Distributions_and_Long_Run_Behavior.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Stationary Distributions and Long Run Behavior of CTMCs

---

## Prompt

Original Prompt can be found [here](https://bookdown.org/kevin_davisross/applied-stochastic-processes/pp-ctmc-longrun.html). A copy of the prompt  can be found on github under [/PracticeProblems/Prompts](https://github.com/NRJaggers/Applied-Stochastic-Processes/tree/main/PracticeProblems/Prompts) along with completed exercises under [/PracticeProblems](https://github.com/NRJaggers/Applied-Stochastic-Processes/tree/main/PracticeProblems).

---

## Problems

###1.

sunny (1), cloudy (2), or rainy (3)

$$
\mathbf{Q} =
\begin{bmatrix}
     & 0.25 & 0\cr
     0.8& & 0.4\cr
     2.0& 1.5& \cr  
\end{bmatrix}
$$

####a.

In the long run, in what state does the city’s weather spend the highest fraction of time? Explain your reasoning without doing any calculations.

The city spends most of its time with sunny weather. If we observe the rate matrix we can see that rates flowing into sunny from other states are the highest. Also if we were to look at the diagonal with flows out of the state, we would see that flow out from the sunny state is the smallest.

####b.

$\pi\mathbf{Q} = 0$

or

$\sum_{i:i\neq j}\pi(i)q(i,j)=\pi(j)\lambda_j$

$\lambda_1\pi(1) = \pi(2)q(2,1) + \pi(3)q(3,1)$

$\lambda_2\pi(2) = \pi(1)q(1,2) + \pi(3)q(3,2)$

$\lambda_3\pi(3) = \pi(1)q(1,3) + \pi(2)q(2,3)$

$1 = \pi(1) + \pi(2) + \pi(3)$

####c.

In [7]:
#use this to allow for running R within Python
%load_ext rpy2.ipython

In [11]:
%%R
compute_stationary_distribution_ctmc <- function(Q){
  s = nrow(Q)
  Pi = rep(1,s) %*% solve(diag(s) - Q + matrix(rep(1, s * s) - diag(s), ncol = s))
  return(Pi)
}

Q = rbind(
  c(-0.25, 0.25, 0),
  c(0.8, -1.2, 0.4),
  c(2.0, 1.5, -3.5)
)

pi_ctmc = compute_stationary_distribution_ctmc(Q)

pi_ctmc

          [,1]      [,2]       [,3]
[1,] 0.7868852 0.1912568 0.02185792


####d.

$\text{P}_t = e^{\mathbf{Q}t}$

In [15]:
import numpy as np
from scipy.linalg import expm

Q = np.array([
    [-0.25, 0.25, 0],
    [0.8, -1.2, 0.4],
    [2.0, 1.5, -3.5]
])

expm(Q * 1)

array([[0.85049267, 0.13693385, 0.01257347],
       [0.53877611, 0.40558487, 0.05563902],
       [0.66797274, 0.27151367, 0.06051359]])

In [17]:
expm(Q * 2)

array([[0.80551322, 0.17541341, 0.01907338],
       [0.71390992, 0.25338253, 0.03270755],
       [0.75481243, 0.21802019, 0.02716739]])

In [19]:
expm(Q * 3)

array([[0.79233214, 0.18662573, 0.02104213],
       [0.76553936, 0.2094071 , 0.02505353],
       [0.77757358, 0.19916138, 0.02326504]])

In [20]:
expm(Q * 4)

array([[0.78847773, 0.18990289, 0.02161937],
       [0.78064424, 0.19656298, 0.02279277],
       [0.78416444, 0.19356977, 0.02226579]])

In [21]:
expm(Q * 5)

array([[0.78735083, 0.19086099, 0.02178818],
       [0.7850606 , 0.19280815, 0.02213125],
       [0.78608982, 0.19193309, 0.02197708]])

In [26]:
expm(Q * 6)

array([[0.78702137, 0.1911411 , 0.02183753],
       [0.78635179, 0.19171038, 0.02193784],
       [0.78665269, 0.19145455, 0.02189276]])

In [27]:
expm(Q * 7)

array([[0.78692504, 0.191223  , 0.02185196],
       [0.78672928, 0.19138943, 0.02188129],
       [0.78681726, 0.19131464, 0.02186811]])

In [28]:
expm(Q * 10)

array([[0.78688624, 0.19125599, 0.02185777],
       [0.78688135, 0.19126014, 0.02185851],
       [0.78688355, 0.19125828, 0.02185818]])

It looks like it takes 4 steps for distributions to start to agree with eachother. Steps 6 and 7 lead to matching values up to 2nd and 3rd decimal places respectively.

###2.

eat (1), play (2), or sleep (3)

$\pi_{DTMC} = (0.4071, 0.2566, 0.3363)$

$\lambda_1 = 2$

$\lambda_2 = 1$

$\lambda_3 = 0.5$

$\pi_{CTMC}(i) = \frac{\pi_{DTMC(i)/\lambda_i}}{\sum_j \pi_{DTMC(j)/\lambda_j}}$

In [51]:
pi = np.array([0.4071, 0.2566, 0.3363])
rate_lambda = np.array([2, 1, 0.5])
v_lambda = 1/rate_lambda

pi_sum = np.dot(pi,v_lambda)

pi_c = np.array([pi[0]*v_lambda[0]/pi_sum, pi[1]*v_lambda[1]/pi_sum, pi[2]*v_lambda[2]/pi_sum])

pi_c


array([0.17969543, 0.22652836, 0.59377621])

---

## Reflection

With each Practice Problem submission, you should also take a few minutes to reflect on the practice problems and related material and thoughtfully respond to the following.

1. Write a sentence or two summarizing - in your own words - one big idea from this material.
2. Describe one particular aspect of this material that you found challenging and why. Then describe how you dealt with the challenge, or what you can do to deal with the challenge.
3. Write at least one specific question you have about this material. I strongly encourage you to post your questions directly in Discord as that's where I'll respond to questions. That is, if you really want an answer to your question - which I hope you do! - please post the question directly in Discord.

The big idea from this material was finding and applying the many analogus concepts from DTMC to CTMC. I feel this exercise went smoothly and I didn't struggle as much when compared to other recent exercises.